### ISSUE TITLE
"mousemove" is considered a valid event in README, but it isn't in code (? not sure)

### ISSUE THREAD

**Issue by troglotit** [filipjelic/react-activity-detector#34]
Pretty much the title. Also, "mousemove" is not in `DEFAULT_ACTIVITY_EVENT`[https://github.com/filipjelic/react-activity-detector/blob/66f15c088bcc7328ccee50e0bef584b214f3df48/src/ActivityDetector.js#L3](https://github.com/filipjelic/react-activity-detector/blob/66f15c088bcc7328ccee50e0bef584b214f3df48/src/ActivityDetector.js#L3)

**Comment by filipjelic** [comment]
@troglotit Thanks for letting me know. It seems it was removed accidentally with the previous pull request(s).
Updated and deployed!

**Comment by troglotit** [comment]
Sorry for bothering more, but do we need to add there too? https://github.com/filipjelic/react-activity-detector/blob/master/index.d.ts#L4

Thanks for super quick response!!!🙇‍♂️
